### PR TITLE
add fix of Eloim for SQL error msg

### PR DESCRIPTION
**Pull request by hibouu**

### CODE REVIEW

**Comment by iglocska** [comment]
The text is spot on, but the image seems to be the wrong one showing the 2.3-2.4 upgrade cleanup script :)

**Comment by hibouu** [comment]
I use this script to fix the problem by me (and it works). But I commit the right script image.

**Comment by iglocska** [comment]
Perfect, thanks a lot!

**Comment by hibouu** [comment]
You're welcome.

**Comment by rotanid** [comment]
just saw this, i dont like the "" in the text...
and the fix itself has nothing to do specifically with the "list servers", something like this can happen almost anywhere i guess?
@iglocska

**Pull request merged**
