### PR TITLE
Update of MISPBook's part Taxonomy

### PR DESCRIPTION
**Pull request by hibouu**
Based on https://www.circl.lu/assets/files/misp-training/first2016/2-MISP-Taxonomies.pdf 
Need review, because I'm not sur that the part about privat Taxinomy is nor yet relevant.

### CODE REVIEW

**Comment by adulau** [comment]
Thank you very much for the contribution.

**Comment by hibouu** [comment]
Gär geschitt. :)

**Comment by cristianbell** [comment]
this is how u say "gern geschehen" in LU? Wow, that's different!

**Comment by hibouu** [comment]
yes, as "you're welcome" in english, or "je vous en prie" in french.

**Pull request merged**
